version: '3.8'

services:
  todo:
    build: .
    container_name: todo-container
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo

  mongo:
    image: mongo:4.4
    container_name: mongo-container
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
